# Generated by Django 3.1 on 2020-09-11 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bug',
            name='seen_by',
            field=models.ManyToManyField(related_name='seen_by_bug_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
